CONFIG_GPIO=y

CONFIG_TRUSTED_EXECUTION_NONSECURE=y

#CONFIG_NO_OPTIMIZATIONS=y
CONFIG_PRINTK=y
CONFIG_CONSOLE=y

# UART logging devzone.nordicsemi.com/.../nrf91-zephyr-enable-lte-logging
CONFIG_LOG=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_UART_CONSOLE=n
CONFIG_RTT_CONSOLE=y

#this option REQUIRES a rtt terminal to be connected
CONFIG_USE_SEGGER_RTT=y
# CONFIG_USE_SEGGER_RTT=n

CONFIG_LOG_BACKEND_RTT=y
# CONFIG_SHELL_BACKEND_RTT=y
# CONFIG_LOG_BACKEND_RTT_MODE_BLOCK=y

CONFIG_PM=y

# ##I2C
CONFIG_I2C=y
CONFIG_I2C_NRFX=y

##FILE SYSTEM SD CARD
CONFIG_DISK_DRIVER_SDMMC=y
CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_FS_FATFS_LFN=y

CONFIG_DISK_ACCESS=y
CONFIG_DISK_DRIVERS=y
CONFIG_SPI=y
# dejan: The following has not been available in ncs since v2.1.0
#CONFIG_SDMMC_OVER_SPI=y
CONFIG_SPI_NRFX_RAM_BUFFER_SIZE=8

##memory
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_HEAP_MEM_POOL_SIZE=16384
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096

##LTE MODEM
CONFIG_NRF_MODEM_LIB=y
# CONFIG_NRF_MODEM_LIB_ON_FAULT_DO_NOTHING is not set
CONFIG_NRF_MODEM_LIB_ON_FAULT_RESET_MODEM=y
# CONFIG_NRF_MODEM_LIB_ON_FAULT_APPLICATION_SPECIFIC is not set
CONFIG_AT_MONITOR=y

# LTE link control
CONFIG_LTE_LINK_CONTROL=y
CONFIG_LTE_AUTO_INIT_AND_CONNECT=n # we want to control all this on the application side
# LTE parameters
## Network Mode / LTE category
# CONFIG_LTE_NETWORK_MODE_LTE_M=y

## PSM
# CONFIG_UDP_PSM_ENABLE=y
# CONFIG_PDN_LEGACY_PCO=y
# CONFIG_LTE_PSM_REQ_RPTAU="00000110"
# CONFIG_LTE_PSM_REQ_RAT="00000101"

## eDRX
# CONFIG_UDP_EDRX_ENABLE=n
# CONFIG_LTE_EDRX_REQ_VALUE_LTE_M="1001"

## RAI
# CONFIG_UDP_RAI_ENABLE=n
# CONFIG_LTE_RAI_REQ_VALUE="4"


CONFIG_NETWORKING=y
CONFIG_NET_NATIVE=n
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_OFFLOAD=y

CONFIG_FTP_CLIENT=y
CONFIG_FTP_CLIENT_KEEPALIVE_TIME=60
CONFIG_FTP_CLIENT_LISTEN_TIME=10
CONFIG_FTP_CLIENT_LOG_LEVEL_INF=y

CONFIG_HTTP_CLIENT=y

CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y

##RTC
CONFIG_DATE_TIME=y
CONFIG_DATE_TIME_MODEM=y
CONFIG_DATE_TIME_NTP=n

##SLEEPY
# CONFIG_LTE_PSM_REQ_RPTAU="10101010"
# CONFIG_LTE_PSM_REQ_RAT="00100001"

# General config
# CONFIG_NEWLIB_LIBC=y
# CONFIG_NCS_SAMPLES_DEFAULTS=y
CONFIG_SERIAL=n

# Network
# CONFIG_NETWORKING=y
# CONFIG_NET_SOCKETS=y

CONFIG_DEBUG_THREAD_INFO=y
CONFIG_THREAD_MONITOR=y
CONFIG_DEBUG_OPTIMIZATIONS=y
# CONFIG_SPEED_OPTIMIZATIONS=y

CONFIG_WATCHDOG=y
CONFIG_WDT_DISABLE_AT_BOOT=n

## reset cause information
CONFIG_HWINFO=y

# Fault diagnostics
CONFIG_RESET_ON_FATAL_ERROR=y
CONFIG_FATAL_ERROR_LOG_LEVEL_DBG=y

# Stack overflow detection
CONFIG_STACK_SENTINEL=y
CONFIG_INIT_STACKS=y
CONFIG_THREAD_STACK_INFO=n

CONFIG_THREAD_ANALYZER=y
CONFIG_THREAD_ANALYZER_AUTO=y
CONFIG_THREAD_NAME=y
CONFIG_THREAD_ANALYZER_AUTO_INTERVAL=1800
CONFIG_LOG_MODE_IMMEDIATE=y

# Optional but useful
CONFIG_REBOOT=y


## FIRMWARE DEBUG CONFIGS ##
CONFIG_DBG_CONFIG_OVERLAY=n

CONFIG_DBG_SEND_IMAGE_RTT=n
CONFIG_DBG_TEST_RUNTIME=n
